
module.exports = {
  // eslint-disable-next-line no-unused-vars
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert('Recipes', [{
    recipe_name: 'Dutch Cocoa Cookies',
    instructions: 'In a mixing bowl, combine the flour, cocoa, salt, and baking soda. \n  In a separate large mixing bowl, cream together the softened butter and sugar.  Then add eggs and vanilla and mix.\n Stir in the flour mixture. \n Chill in refrigerator for 1-2 hours. \n Preheat the oven to 350 degrees F.  Then roll the dough into balls about 1 inch in diameter and roll them in granulated sugar to coat. \n Bake on an ungreased cookie sheet for 11-12 minutes, careful not to overbake.',
    serving_size: '2-3 dozen',
    category: 'Desserts',
    dietary_restriction: 'none',
    special_notes: 'Make sure you use Dutch Process Cocoa!',
    image: '/assets/images/uploads/Dutch-Cocoa-Cookies.jpg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Almond Yellow Cake',
    instructions: 'Preheat oven to 350 degrees F. \n In a large bowl, combine the flour, sugar, baking powder and salt. \n Add the milk, vegetable oil, and softened butter to the flour mixture and beat on medium/high for 2 minutes. \n Add the eggs, vanilla, and almond extract and beat again on medium/high speed for 2 additional minutes. \n Pour into 2 round 9-inch cake pans and bake for 20-25 minutes. \n Allow to cool before frosting with your favorite frosting!',
    serving_size: '12',
    category: 'Desserts',
    dietary_restriction: 'none',
    special_notes: '',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Chicken Tortilla Soup',
    instructions: 'In a large pot, saute oil, onion, garlic and peppers for just a few minutes until they begin to soften. \n Add all of the other ingredients, including the whole chicken breasts, bring to a boil, then cover and simmer for 30 minutes. \n Pull the chicken breasts out of the pot and shred them apart using forks.  Return the shredded chicken to the pot. \n Season with salt and pepper to taste and serve with tortilla chips.',
    serving_size: '6',
    category: 'Soups',
    dietary_restriction: 'none',
    special_notes: 'Add some fresh lime juice before serving!',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Garlic Sauce',
    instructions:
      'Place all ingredients except oil in food processor or blender and process until smooth. Slowly add oil while motor is running. \n Process or blend until mixture is slightly thickened. Serve over Grilled Garlic Halibut and green beans',
    serving_size: '2-4 servings',
    category: 'other',
    dietary_restriction: 'none',
    special_notes: 'Tip: While the meat is cooking, you can make your rice and steam a bag of broccoli in the microwave.',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 5,
  }, {
    recipe_name: 'Grilled Garlic Halibut',
    instructions:
      'Using a charcoal grill, start coals before meal preparation. In a small bowl, mix oil, salt, red pepper, and garlic. Spread on both sides of halibut steaks. Cover and grill on oiled grill 4 inches from medium coals 10 to 15 minutes or until fish flakes easily with a fork.  Sprinkle with cilantro.',
    serving_size: '4',
    category: 'entree',
    dietary_restriction: 'none',
    special_notes: '',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 5,
  }, {
    recipe_name: 'Grilled Texas Toast',
    instructions:
      'Spread margarine or butter on both sides of bread slices. Sprinkle with seasoned salt. Grill bread 4 inches from medium coals 4 to 6 minutes, turning once, until golden brown.',
    serving_size: '4',
    category: 'side',
    dietary_restriction: 'none',
    special_notes: '',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 3,
  }, {
    recipe_name: 'Savory Broiled Cod',
    instructions:
      'Set oven control to broil.  Grease rack in broiler pan.  Place cod on rack.  Broil 4 inches from heat 8 minutes.  Mix remaining ingredients in small bowl.  Spread on both sides fish.  Broil 1 to 2 minutes or until topping is light brown and fish flakes easily with fork.',
    serving_size: '4',
    category: 'entree',
    dietary_restriction: 'none',
    special_notes: '',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 4,
  }, {
    recipe_name: 'Beef Teriyaki Skillet',
    instructions:
      'In a large skillet preheat 1 teaspoon sesame oil over medium-high heat for about 1 minute. The sesame oil adds great flavor to the dish, but if you don’t have any you can substitute with canola or vegetable oil. \n Add beef, onion, garlic and ginger to the skillet. Cook, breaking up the meat as you stir, until the beef is no longer pink and the onion is tender (about 5-7 minutes). Drain, and return meat to skillet. \n Stir teriyaki sauce into the beef mixture. Bring to a low simmer and cook for an additional 3-5 minutes, just until sauce thickens slightly. \n Serve over rice, in tortillas, or in lettuce wraps.',
    serving_size: '4',
    category: 'entree',
    dietary_restriction: 'none',
    special_notes: '10-Minute Recipe',
    image: '/assets/images/uploads/Beef-Teriyaki-Skillet.jpg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 2,
  }, {
    recipe_name: 'Homemade Teriyaki Sauce',
    instructions:
      'Combine 1 cup water, soy sauce, brown sugar, honey, ginger, and garlic powder in a saucepan over medium heat. Cook until nearly heated through, about 1 minute.  Mix cornstarch and 1/4 cold water together in a cup; stir until dissolved. Add to the saucepan. Cook and stir sauce until thickened, 5 to 7 minutes.',
    serving_size: '4',
    category: 'other',
    dietary_restriction: 'vegan',
    special_notes: '10-Minute Recipe',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 5,
  }, {
    recipe_name: 'Lemon English Muffins',
    instructions: 'Set oven control to broil.  Place muffins, cut sides up, on rack in broiler pan.  Broil 4 inches from heat 2 to 3 minutes or until golden brown.  Mix margarine or butter, honey, and lemon peel.  Spread over hot muffins',
    serving_size: '4',
    category: 'bread',
    dietary_restriction: 'none',
    special_notes: '',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Black Bean Salad with Chili Dressing',
    instructions: 'Prepare Chili Dressing in large glass or plastic bowl.  Mix together red wine vinegar, vegetable oil, chili powder, cumin, and crushed garlic.  Stir in the remaining ingredients',
    serving_size: '4',
    category: 'salad',
    dietary_restriction: 'none',
    special_notes: 'Canned black beans may be used, cooked and drained',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Chili-Cheese Tortillas',
    instructions: 'Heat oven to 350 degrees.  Spread about 1 tablespoon chilies on each tortilla.  Sprinkle each with scant 2 tablespoons cheese.  Roll up tightly. (Secure with toothpicks if necessary.) Place with seam sides down in ungreased square pan, 9x9x2 inches.  Cover with aluminum foil.  Bake about 15 minutes or until warm.',
    serving_size: '4',
    category: 'App',
    dietary_restriction: 'vegan',
    special_notes: 'buying pre-diced chilies to cuts down on chopping time',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 2,
  }, {
    recipe_name: 'Deviled Eggs',
    instructions: 'Fill a saucepan with an inch of water and insert a steamer basket.  Bring the water to a boil and place the eggs in the steamer basket, Cover the pan and let eggs steam for 17 minutes per dozen eggs.Then shock with cold water and peel shells off. Using sharp knife, cut eggs in half, lengthwise.  Carefully remove yolks.  Place yolks in small mixing bowl and set aside.  Place the egg white halves on serving platter, arranging them for presentation and refrigerate.  Take bowl of yolks and with a fork, mash yolks and add mustard, mayonnaise, onion, Tabasco, and sprinking of salt and pepper.  Add more mayonnaise to get the desired consistency.  Grab refrigerated egg whites on platter.  Spoon mixture into egg white halves.  Sprinkle with paprika.  Refrigerate until ready to serve.',
    serving_size: '2 dozen',
    category: 'app',
    dietary_restriction: 'gluten-free',
    special_notes: '',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Gluten-Free Coconut Bread',
    instructions: 'Place a rack in middle of oven; preheat to 350°. Line a 9x5" loaf pan with parchment, leaving overhang on long sides; coat with nonstick spray (to use an 8½x4½" pan, hold back 1 cup batter). Toast shredded coconut on a rimmed baking sheet, tossing occasionally, until lightly browned, 5–7 minutes. Let cool. Whisk rice flour, sorghum flour, tapioca starch, baking powder, baking soda, salt, and xanthan gum in a medium bowl. Using an electric mixer on medium speed, beat sugar, coconut milk, oil, and coconut extract, if using, in a large bowl until sugar is dissolved and mixture is smooth, about 4 minutes. Add eggs one at a time, beating well after each addition. Beat mixture until very smooth, about 2 minutes. Reduce speed to low; beat in dry ingredients. Increase speed to medium; beat batter 5 minutes. Beat in toasted coconut. Scrape batter into prepared pan; top with coconut flakes. Bake bread until top springs back when gently pressed and a tester inserted all the way to the bottom comes out with just a few moist crumbs attached, 80–95 minutes. Transfer pan to a wire rack and let bread cool in pan 10 minutes. Turn out bread onto rack and let cool completely.',
    serving_size: '8',
    category: 'bread',
    dietary_restriction: 'gluten-free',
    special_notes: 'Xanthan gum can be found at natural foods stores, some supermarkets, and online.',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Easy Breakfast Quesadillas',
    instructions: 'In a medium bowl, whisk eggs, milk, salt and pepper. Add green peppers and stir to combine (see special notes). Set aside. In a large skillet, melt 2 tablespoons butter over medium heat. Add egg mixture and cook until no longer runny, stirring often. Remove eggs to separate plate. In the same skillet (wipe, if needed), melt 2 tablespoons butter over medium heat. Place one tortilla shell in middle of pan. Top with 1/4 cup cheese, leaving a ½ inch border around tortilla. Spread eggs in an even layer on top of cheese, followed by bacon and a sprinkling of more cheese, if desired. Place second tortilla shell on top of egg mixture and lightly press down. Heat for 2-3 minutes on both sides, or until shell is slightly golden and cheese is melted. Repeat with remaining tortilla shells. Serve immediately.',
    serving_size: '3',
    category: 'breakfast',
    dietary_restriction: 'none',
    special_notes: 'You may chose not to sauté the green peppers before adding to the eggs, which keeps them slightly crunchy. If you prefer softened green peppers, sauté them in a tablespoon of unsalted butter/oil until softened before adding to eggs.',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Mushroom & Potato Pizza',
    instructions: 'Sprinkle counter surface with flour before rolling dough on it so dough does not stick to the counter.  Roll out pizza dough with rolling pin.  Stretch and place on either 12 inch round or 9 by 13 inch rectangular baking tray. Assemble pizza using tomato sauce- first smear on dough with spoon and then continue assembling pizza using fontina cheese, red potatoes, cremini mushroom, chopped garlic, shredded spinach, and rosemary.  Bake at 400 degrees for 15 to 20 minutes, checking after 13 minutes. Remove from oven and let cool.  Sprinkle crushed red pepper flakes and grated parmesan cheese to taste.  Enjoy!',
    serving_size: '3',
    category: 'Entree',
    dietary_restriction: 'none',
    special_notes: 'add salt and pepper to taste',
    image: '/assets/images/uploads/MushroomPotatoPizza.jpg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 5,
  }, {
    recipe_name: 'Tuna Patties',
    instructions: 'In a bowl, mix tuna, bread, milk, and egg.  Knead all ingredients together and form into patties. In medium size skillet add oil and  fry patties on low to medium heat until browned on both sides. Enjoy!',
    serving_size: '4',
    category: 'Entree',
    dietary_restriction: 'none',
    special_notes: 'add additional slices of bread as desired to allow mixture to form into patties',
    image: '/assets/images/uploads/TunaPatties.jpg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 5,
  }, {
    recipe_name: 'Vanilla Biscotti',
    // eslint-disable-next-line quotes
    instructions: `Preheat the oven to 350°F. Lightly grease (or line with parchment) one large (about 18" x 13") baking sheet. In a medium-sized bowl, beat the butter, sugar, salt, vanilla, almond extract (if you're using it), and baking powder until the mixture is smooth and creamy. Beat in the eggs; the batter may look slightly curdled. At low speed of your mixer, add the flour, stirring until smooth; the dough will be sticky. Plop the dough onto the prepared baking sheet. Divide it in half, and shape it into two 9 1/2" x 2" logs, about 3/4" tall. Straighten the logs, and smooth their tops and sides; a wet spatula or wet bowl scraper works well here. Bake the dough for 25 minutes. Remove it from the oven. Using a spray bottle filled with room-temperature water, lightly but thoroughly spritz the logs, making sure to cover the sides as well as the top. Softening the crust just this little bit will make slicing the biscotti much easier. Reduce the oven temperature to 325°F. Wait 5 minutes, then use a sharp chef's knife or serrated knife to cut the log crosswise into 1/2" to 3/4" slices. Or cut the biscotti on the diagonal, for fewer, longer biscotti. As you're slicing, be sure to cut straight up and down, perpendicular to the pan; if you cut unevenly, biscotti may be thicker at the top than the bottom, and they'll topple over during their second bake. Set the biscotti on edge on the prepared baking sheet. Return the biscotti to the oven, and bake them for 25 to 30 minutes, until they feel very dry and are beginning to turn golden. They'll still feel a tiny bit moist in the very center, if you break off a piece; but they'll continue to dry out as they cool. Remove the biscotti from the oven, and transfer them to a rack to cool. Store airtight at room temperature; they'll stay good for weeks.`,
    serving_size: 'About 30 biscotti, depending on size',
    category: 'Desserts',
    dietary_restriction: 'none',
    special_notes: 'There are so many options to switch these up with mix-ins! Add dried cranberries, chocolate chips, nuts, zests, and different extracts to play with the flavors!',
    image: '/assets/images/uploads/vanilla_biscotti53281k.jpg',
    url_source: 'https://www.kingarthurflour.com/recipes/american-style-vanilla-biscotti-recipe',
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Lamb Stew',
    instructions: 'In a large dutch oven or pot over medium-high heat, heat oil. Add lamb and cook on all sides until seared, 10 minutes, working in batches if necessary. Transfer to a plate. In the same pot, cook onion, chopped carrots, and chopped celery until soft, 5 minutes. Season with salt and pepper. Add garlic, tomato paste, cumin, and paprika and cook until garlic is fragrant and tomato paste has darkened, 2 minutes. Add lamb back to dutch oven then add broth, wine, Worcestershire sauce, rosemary, and bay leaves. Bring to a boil then reduce heat to a simmer. Season with salt and pepper. Cover and let simmer until lamb is tender, 30 minutes. Add potatoes and simmer, covered, until potatoes are tender and stew has thickened, 30 minutes. Remove bay leaves and rosemary and garnish with parsley before serving.',
    serving_size: '6',
    category: 'Soups',
    dietary_restriction: 'none',
    special_notes: 'Make sure you use SMOKED paprika!',
    image: '/assets/images/uploads/LambStew.jpg',
    url_source: 'https://www.delish.com/cooking/recipe-ideas/a26951897/lamb-stew-recipe/',
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 6,
  }, {
    recipe_name: 'Blueberry Lemon Bread',
    instructions: 'Preheat the oven to 325 degrees Fahrenheit and spray a loaf pan with cooking spray. Combine the flour, baking powder and salt in a small bowl and then set aside. In a larger bowl, cream together the butter and sugar. Add eggs one at a time and mix, then add the lemon zest. Mix in the dry ingredients a little at a time, alternating with the milk. Fold in the blueberries and then spoon the batter into the prepared loaf pan. Bake for 75 minutes- the top should be golden. While the bread starts to cool, prepare the glaze by heating the lemon juice and sugar in a small saucepan on the stove until the sugar is dissolved. Pierce the top of the loaf with a toothpick to make holes for the glaze to seep into. Spoon the glaze over the hot loaf. Allow to cool completely before slicing.',
    serving_size: '1 loaf',
    category: 'Bread',
    dietary_restriction: 'Vegetarian',
    special_notes: '',
    image: '/assets/images/uploads/20200710_144802.jpg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Air Fryer Chicken Wings',
    instructions: 'Pre-heat air fryer to 400 F Add oil to a large bowl Add the wings and coat with Pixie Dust Seasoning Toss to combine Add a single layer of wings to the air fryer. Cook for 20 minutes, flipping halfway.',
    serving_size: '4',
    category: 'App',
    dietary_restriction: 'none',
    special_notes: 'You can find Pixie Dust Seasoning at Whole Foods',
    image: '/assets/images/uploads/Air-Fryer-Chicken-Wings.jpg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 2,
  }, {
    recipe_name: 'Air Fryer Buffalo Cauliflower',
    instructions: 'Make the buffalo sauce: Add melted butter and Franks Red Hot Sauce to a small bowl. Whisk to combine and set aside. If it thickens too much, microwave for 30 seconds and whisk again. Set aside. In the large bowl, add the cauliflower and pour the buffalo sauce over the top. Toss gently to completely coat cauliflower; set aside. Using a zip lock bag, panko bread crumbs, regular bread crumbs, and all seasonings; Shake to combine. Add about half of the coated cauliflower to the bag and toss/shake to coat the cauliflower. Using tongs, remove from the bag and place into the air fryer in a single layer. Repeat for the rest of the cauliflower. **Depending on the size of your air fryer, you may need to cook in 2 batches - do not overcrowd the bites!** Cook at 400 degrees for 7 minutes. Remove tray and gently flip cauliflower or shake. Place tray back into unit and cook at 400 degrees for 5 more minutes. Remove and set aside. Cook second batch if needed.',
    serving_size: '6',
    category: 'App',
    dietary_restriction: 'Vegetarian',
    special_notes: 'Serve with blue cheese or ranch.',
    image: '/assets/images/uploads/air-fryer-cauli.jpg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 2,
  }, {
    recipe_name: 'NY Style Pizza',
    // eslint-disable-next-line quotes
    instructions: `Start the dough by combining the water, sugar and yeast in a large bowl and let sit for a few minutes. If the yeast goes foamy, it's alive and you're good to proceed (if it doesn't, it's dead and you need new yeast). Add the olive oil and salt and 5 cups (600g) of bread flour. Mix until just combined, then start kneading. Add just enough additional flour to keep the dough workable (i.e. not too sticky) and knead until you can stretch some of the dough into a thin sheet without it tearing. (NOTE: You will probably need to add a lot more flour. The quantity I give here is just a baseline to get you started.) Divide the dough into four equal balls and put them in four containers (ideally glass) and lightly coat the balls and the interior of their containers with olive oil. Cover, and either rise at room temperature for two hours, or put them in the refrigerator and let them rise for 1-7 days. (I prefer the long, cold rise.) When you want to bake, put a pizza stone or pizza steel into your oven (mine works best on a high rack position but every oven is different) and preheat to your highest possible temperature, ideally convection, for a full hour. For the sauce, simply mix together the ingredients. Liberally dust a pizza peel with cornmeal (or something similar). Take the cold dough out of the fridge and dust it in flour. Stretch to the widest size and shape that will fit on your peel and stone/steel. Top with just enough sauce to lightly coat the surface. Dust the sauce layer with parmesan, then cover with the mozzarella. Transfer the pizza to the stone/steel and bake until the crust is well-browned and the cheese has browned a bit (but, ideally, has not started oozing out an orange grease layer), 6-7 minutes.`,
    serving_size: '3',
    category: 'Entree',
    dietary_restriction: 'vegetarian',
    special_notes: 'A super hot oven, pizza stone, and slow cold rise are key factors to making this recipe a success.',
    image: '/assets/images/uploads/NYStylePizza.jpg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 3,
  }, {
    recipe_name: 'Banana Poppy Bread for the Bread Machine',
    instructions: '1. Put the ingredients in the order listed in the bread machine container 2. Select sweet bread, 2.0 lbs and light crust 3. Press start and wait 4 Enjoy!',
    serving_size: '12',
    category: 'Bread',
    dietary_restriction: 'Vegetarian',
    special_notes: 'You can substitute the oil for 4 oz applesauce',
    image: '/assets/images/uploads/bananapoppy.jpeg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 4,
  }, {
    recipe_name: 'Blueberry Dutch Baby',
    instructions: 'Step 1 Preheat the oven to 425 degrees F (220 degrees C). Step 2 Combine flour, salt, vanilla extract, eggs, and milk in a high-speed blender. Blend on high speed until completely smooth and very thin, about 1 minute. Step 3 Heat a 9- or 10-inch cast iron skillet over high heat. Pour clarified butter into the skillet and use a pastry brush to grease the sides. Heat butter until just starting to smoke. Step 4 Quickly and carefully pour the batter into the center of the skillet, then sprinkle blueberries over top. Transfer skillet to the center of the preheated oven and bake until browned and nicely puffed, 20 to 25 minutes. Step 5 Carefully remove from the oven and immediately brush the top with melted butter. Squeeze lemon juice over top as Dutch baby deflates. Dust with powdered sugar. Step 6 Cut in wedges to serve and drizzle with maple syrup.',
    serving_size: '2',
    category: 'Breakfast',
    dietary_restriction: 'Vegetarian',
    special_notes: '',
    image: '/assets/images/uploads/BlueberryDutchBaby.jpg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 3,
  }, {
    recipe_name: 'Brownies',
    instructions: 'Preheat oven to 350º F grease and flour 8" square pan Melt the butter in a large saucepan then remove from heat stir sugar, eggs and vanilla beat in cocoa powder, flour, salt and baking powder Pour into pan and into oven for 25-30 minutes Enjoy!',
    serving_size: '16',
    category: 'Desserts',
    dietary_restriction: 'none',
    special_notes: '',
    image: '/assets/images/uploads/IMG_4371.jpg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 4,
  }, {
    recipe_name: 'Pasta Salad',
    instructions: 'In a large pot of salted boiling water, cook pasta until al dente, rinse under cold water and drain. Whisk together the salad spice mix and Italian dressing. In a salad bowl, combine the pasta, cherry tomatoes, bell peppers and olives. Pour dressing over salad; toss and refrigerate overnight.',
    serving_size: '6',
    category: 'Salad',
    dietary_restriction: 'Vegetarian',
    // eslint-disable-next-line quotes
    special_notes: `Don't skip the overnight wait. That allows the flavors to meld and gives this pasta salad a special touch.`,
    image: '/assets/images/uploads/pasta-salad.jpeg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 4,
  }, {
    recipe_name: 'Spinach Pomegranate Salad',
    instructions: 'Place spinach in a salad bowl. Top with shallot walnuts feta. Sprinkle pomegranate seeds over the top and drizzle with vinaigrette. Optional: Toast the sesame seed on a hot pan for 5 minutes. Sprinkle on top',
    serving_size: '6',
    category: 'Salad',
    dietary_restriction: 'Vegetarian',
    special_notes: '',
    image: '/assets/images/uploads/spinach-salad.jpeg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 6,
  }, {
    recipe_name: 'Real Poutine',
    instructions: 'Heat oil in a deep fryer or deep heavy skillet to 365 degrees F (185 degrees C). While the oil is heating, you can begin to warm your gravy. Make the fries in batches if necessary to allow them room to move a little in the oil. Remove to a paper towel lined plate to drain. Place the fries on a serving platter, and sprinkle the cheese over them. Ladle gravy over the fries and cheese, and serve immediately.',
    serving_size: '4',
    category: 'Side',
    dietary_restriction: 'none',
    special_notes: '',
    image: '/assets/images/uploads/poutine.jpeg',
    url_source: 'https://www.allrecipes.com/recipe/79300/real-poutine/',
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 7,
  }], {}),

};
