
module.exports = {
  // eslint-disable-next-line no-unused-vars
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert('Recipes', [{
    recipe_name: 'Dutch Cocoa Cookies',
    instructions: 'In a mixing bowl, combine the flour, cocoa, salt, and baking soda. \n  In a separate large mixing bowl, cream together the softened butter and sugar.  Then add eggs and vanilla and mix.\n Stir in the flour mixture. \n Chill in refrigerator for 1-2 hours. \n Preheat the oven to 350 degrees F.  Then roll the dough into balls about 1 inch in diameter and roll them in granulated sugar to coat. \n Bake on an ungreased cookie sheet for 11-12 minutes, careful not to overbake.',
    serving_size: '2-3 dozen',
    category: 'Desserts',
    dietary_restriction: 'none',
    special_notes: 'Make sure you use Dutch Process Cocoa!',
    image: '/assets/images/uploads/Dutch-Cocoa-Cookies.jpg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Almond Yellow Cake',
    instructions: 'Preheat oven to 350 degrees F. \n In a large bowl, combine the flour, sugar, baking powder and salt. \n Add the milk, vegetable oil, and softened butter to the flour mixture and beat on medium/high for 2 minutes. \n Add the eggs, vanilla, and almond extract and beat again on medium/high speed for 2 additional minutes. \n Pour into 2 round 9-inch cake pans and bake for 20-25 minutes. \n Allow to cool before frosting with your favorite frosting!',
    serving_size: '12',
    category: 'Desserts',
    dietary_restriction: 'none',
    special_notes: '',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Chicken Tortilla Soup',
    instructions: 'In a large pot, saute oil, onion, garlic and peppers for just a few minutes until they begin to soften. \n Add all of the other ingredients, including the whole chicken breasts, bring to a boil, then cover and simmer for 30 minutes. \n Pull the chicken breasts out of the pot and shred them apart using forks.  Return the shredded chicken to the pot. \n Season with salt and pepper to taste and serve with tortilla chips.',
    serving_size: '6',
    category: 'Soups',
    dietary_restriction: 'none',
    special_notes: 'Add some fresh lime juice before serving!',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Garlic Sauce',
    instructions:
      'Place all ingredients except oil in food processor or blender and process until smooth. Slowly add oil while motor is running. \n Process or blend until mixture is slightly thickened. Serve over Grilled Garlic Halibut and green beans',
    serving_size: '2-4 servings',
    category: 'other',
    dietary_restriction: 'none',
    special_notes: 'Tip: While the meat is cooking, you can make your rice and steam a bag of broccoli in the microwave.',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 5,
  }, {
    recipe_name: 'Grilled Garlic Halibut',
    instructions:
      'Using a charcoal grill, start coals before meal preparation. In a small bowl, mix oil, salt, red pepper, and garlic. Spread on both sides of halibut steaks. Cover and grill on oiled grill 4 inches from medium coals 10 to 15 minutes or until fish flakes easily with a fork.  Sprinkle with cilantro.',
    serving_size: '4',
    category: 'entree',
    dietary_restriction: 'none',
    special_notes: '',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 5,
  }, {
    recipe_name: 'Grilled Texas Toast',
    instructions:
      'Spread margarine or butter on both sides of bread slices. Sprinkle with seasoned salt. Grill bread 4 inches from medium coals 4 to 6 minutes, turning once, until golden brown.',
    serving_size: '4',
    category: 'side',
    dietary_restriction: 'none',
    special_notes: '',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 3,
  }, {
    recipe_name: 'Savory Broiled Cod',
    instructions:
      'Set oven control to broil.  Grease rack in broiler pan.  Place cod on rack.  Broil 4 inches from heat 8 minutes.  Mix remaining ingredients in small bowl.  Spread on both sides fish.  Broil 1 to 2 minutes or until topping is light brown and fish flakes easily with fork.',
    serving_size: '4',
    category: 'entree',
    dietary_restriction: 'none',
    special_notes: '',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 4,
  }, {
    recipe_name: 'Beef Teriyaki Skillet',
    instructions:
      'In a large skillet preheat 1 teaspoon sesame oil over medium-high heat for about 1 minute. The sesame oil adds great flavor to the dish, but if you don’t have any you can substitute with canola or vegetable oil. \n Add beef, onion, garlic and ginger to the skillet. Cook, breaking up the meat as you stir, until the beef is no longer pink and the onion is tender (about 5-7 minutes). Drain, and return meat to skillet. \n Stir teriyaki sauce into the beef mixture. Bring to a low simmer and cook for an additional 3-5 minutes, just until sauce thickens slightly. \n Serve over rice, in tortillas, or in lettuce wraps.',
    serving_size: '4',
    category: 'entree',
    dietary_restriction: 'none',
    special_notes: '10-Minute Recipe',
    image: '/assets/images/uploads/Beef-Teriyaki-Skillet.jpg',
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 2,
  }, {
    recipe_name: 'Homemade Teriyaki Sauce',
    instructions:
      'Combine 1 cup water, soy sauce, brown sugar, honey, ginger, and garlic powder in a saucepan over medium heat. Cook until nearly heated through, about 1 minute.  Mix cornstarch and 1/4 cold water together in a cup; stir until dissolved. Add to the saucepan. Cook and stir sauce until thickened, 5 to 7 minutes.',
    serving_size: '4',
    category: 'other',
    dietary_restriction: 'vegan',
    special_notes: '10-Minute Recipe',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 5,
  }, {
    recipe_name: 'Lemon English Muffins',
    instructions: 'Set oven control to broil.  Place muffins, cut sides up, on rack in broiler pan.  Broil 4 inches from heat 2 to 3 minutes or until golden brown.  Mix margarine or butter, honey, and lemon peel.  Spread over hot muffins',
    serving_size: '4',
    category: 'bread',
    dietary_restriction: 'none',
    special_notes: '',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Black Bean Salad with Chili Dressing',
    instructions: 'Prepare Chili Dressing in large glass or plastic bowl.  Mix together red wine vinegar, vegetable oil, chili powder, cumin, and crushed garlic.  Stir in the remaining ingredients',
    serving_size: '4',
    category: 'salad',
    dietary_restriction: 'none',
    special_notes: 'Canned black beans may be used, cooked and drained',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Chili-Cheese Tortillas',
    instructions: 'Heat oven to 350 degrees.  Spread about 1 tablespoon chilies on each tortilla.  Sprinkle each with scant 2 tablespoons cheese.  Roll up tightly. (Secure with toothpicks if necessary.) Place with seam sides down in ungreased square pan, 9x9x2 inches.  Cover with aluminum foil.  Bake about 15 minutes or until warm.',
    serving_size: '4',
    category: 'App',
    dietary_restriction: 'vegan',
    special_notes: 'buying pre-diced chilies to cuts down on chopping time',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 2,
  }, {
    recipe_name: 'Deviled Eggs',
    instructions: 'Fill a saucepan with an inch of water and insert a steamer basket.  Bring the water to a boil and place the eggs in the steamer basket, Cover the pan and let eggs steam for 17 minutes per dozen eggs.Then shock with cold water and peel shells off. Using sharp knife, cut eggs in half, lengthwise.  Carefully remove yolks.  Place yolks in small mixing bowl and set aside.  Place the egg white halves on serving platter, arranging them for presentation and refrigerate.  Take bowl of yolks and with a fork, mash yolks and add mustard, mayonnaise, onion, Tabasco, and sprinking of salt and pepper.  Add more mayonnaise to get the desired consistency.  Grab refrigerated egg whites on platter.  Spoon mixture into egg white halves.  Sprinkle with paprika.  Refrigerate until ready to serve.',
    serving_size: '2 dozen',
    category: 'app',
    dietary_restriction: 'gluten-free',
    special_notes: '',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Gluten-Free Coconut Bread',
    instructions: 'Place a rack in middle of oven; preheat to 350°. Line a 9x5" loaf pan with parchment, leaving overhang on long sides; coat with nonstick spray (to use an 8½x4½" pan, hold back 1 cup batter). Toast shredded coconut on a rimmed baking sheet, tossing occasionally, until lightly browned, 5–7 minutes. Let cool. Whisk rice flour, sorghum flour, tapioca starch, baking powder, baking soda, salt, and xanthan gum in a medium bowl. Using an electric mixer on medium speed, beat sugar, coconut milk, oil, and coconut extract, if using, in a large bowl until sugar is dissolved and mixture is smooth, about 4 minutes. Add eggs one at a time, beating well after each addition. Beat mixture until very smooth, about 2 minutes. Reduce speed to low; beat in dry ingredients. Increase speed to medium; beat batter 5 minutes. Beat in toasted coconut. Scrape batter into prepared pan; top with coconut flakes. Bake bread until top springs back when gently pressed and a tester inserted all the way to the bottom comes out with just a few moist crumbs attached, 80–95 minutes. Transfer pan to a wire rack and let bread cool in pan 10 minutes. Turn out bread onto rack and let cool completely.',
    serving_size: '8',
    category: 'bread',
    dietary_restriction: 'gluten-free',
    special_notes: 'Xanthan gum can be found at natural foods stores, some supermarkets, and online.',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }, {
    recipe_name: 'Easy Breakfast Quesadillas',
    instructions: 'In a medium bowl, whisk eggs, milk, salt and pepper. Add green peppers and stir to combine (see special notes). Set aside. In a large skillet, melt 2 tablespoons butter over medium heat. Add egg mixture and cook until no longer runny, stirring often. Remove eggs to separate plate. In the same skillet (wipe, if needed), melt 2 tablespoons butter over medium heat. Place one tortilla shell in middle of pan. Top with 1/4 cup cheese, leaving a ½ inch border around tortilla. Spread eggs in an even layer on top of cheese, followed by bacon and a sprinkling of more cheese, if desired. Place second tortilla shell on top of egg mixture and lightly press down. Heat for 2-3 minutes on both sides, or until shell is slightly golden and cheese is melted. Repeat with remaining tortilla shells. Serve immediately.',
    serving_size: '3',
    category: 'breakfast',
    dietary_restriction: 'none',
    special_notes: 'You may chose not to sauté the green peppers before adding to the eggs, which keeps them slightly crunchy. If you prefer softened green peppers, sauté them in a tablespoon of unsalted butter/oil until softened before adding to eggs.',
    image: null,
    url_source: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    AuthorId: 1,
  }], {}),

};
